language: {language}
services:
  ticket_manager: 
    name: GitHub
    owner: {owner}
    project_id: '{project_id}'
    url: {project_url}
    lane_map:
      ready: 'Todo'
      working: 'In Progress'
      done: 'Done'
  code_hosting_service:
    name: GitHub
    owner: {owner}
