language: {language}
repositories:
  - name: {repository_name}
services:
  ticket_manager: 
    name: GitHub
    owner: {owner}
    project_id: '{project_id}'
    url: {project_url}
    lane_map:
      ready: 'Todo'
      working: 'In Progress'
      done: 'Done'
  code_hosting_service: 
    name: GitHub
    owner: {owner}
    repo_base_url: {repo_base_url}
