"""Guard against drift between the Click definitions and docs/cli_reference.md.

The reference is generated by scripts/generate-cli-reference.py; this test
regenerates it and fails when the committed file was not regenerated after a
CLI change.
"""

from __future__ import annotations

import importlib.util
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
GENERATOR_PATH = REPO_ROOT / "scripts" / "generate-cli-reference.py"
REFERENCE_PATH = REPO_ROOT / "docs" / "cli_reference.md"


def _load_generator():
    spec = importlib.util.spec_from_file_location(
        "generate_cli_reference", GENERATOR_PATH
    )
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_cli_reference_is_up_to_date() -> None:
    generator = _load_generator()
    assert REFERENCE_PATH.exists(), f"{REFERENCE_PATH} is missing."
    assert REFERENCE_PATH.read_text() == generator.build_reference(), (
        f"{REFERENCE_PATH} is out of date for the current Click definitions. "
        f"Regenerate it with: {generator.REGENERATE_COMMAND}"
    )
